import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { api } from '../servicos/api';

const inicial = { titulo: '', materia: '', tipo: 'tarefa', dataEntrega: '', horarioEntrega: '23:59', prioridade: 'media', descricao: '' };

export function PaginaNovaTarefa() {
  const navegar = useNavigate();
  const [dados, setDados] = useState(inicial);
  const [erro, setErro] = useState('');
  const [enviando, setEnviando] = useState(false);
  const alterar = (evento) => setDados({ ...dados, [evento.target.name]: evento.target.value });
  async function enviar(evento) { evento.preventDefault(); setErro(''); if (!dados.titulo || !dados.dataEntrega) { setErro('Preencha o título e a data de entrega.'); return; } setEnviando(true); try { await api.criarTarefa({ ...dados, dataEntrega: `${dados.dataEntrega}T${dados.horarioEntrega}:00` }); navegar('/tarefas'); } catch (erroApi) { setErro(erroApi.message); } finally { setEnviando(false); } }
  return <><header className="cabecalho-pagina"><div><p className="etiqueta">Lembraí · novo registro</p><h1>Nova tarefa</h1><p className="subtitulo">Preencha o essencial. A Lembraí cuida do lembrete.</p></div></header><div className="cartao formulario-cartao">{erro && <div className="alerta erro">{erro}</div>}<form onSubmit={enviar}><div className="formulario-grid"><div className="campo largo"><label htmlFor="titulo">O que você precisa fazer?</label><input id="titulo" name="titulo" value={dados.titulo} onChange={alterar} placeholder="Ex.: Trabalho de Banco de Dados" required /></div><div className="campo"><label htmlFor="materia">Matéria</label><input id="materia" name="materia" value={dados.materia} onChange={alterar} placeholder="Ex.: Sistemas de Informação" /></div><div className="campo"><label htmlFor="tipo">Tipo</label><select id="tipo" name="tipo" value={dados.tipo} onChange={alterar}><option value="tarefa">Tarefa</option><option value="prova">Prova</option><option value="trabalho">Trabalho</option><option value="aula">Aula</option><option value="compromisso">Compromisso</option></select></div><div className="campo"><label htmlFor="dataEntrega">Data de entrega</label><input id="dataEntrega" name="dataEntrega" type="date" value={dados.dataEntrega} onChange={alterar} required /></div><div className="campo"><label htmlFor="horarioEntrega">Horário</label><input id="horarioEntrega" name="horarioEntrega" type="time" value={dados.horarioEntrega} onChange={alterar} /></div><div className="campo"><label htmlFor="prioridade">Prioridade</label><select id="prioridade" name="prioridade" value={dados.prioridade} onChange={alterar}><option value="baixa">Baixa</option><option value="media">Média</option><option value="alta">Alta</option></select></div><div className="campo largo"><label htmlFor="descricao">Observações <span className="subtitulo">(opcional)</span></label><textarea id="descricao" name="descricao" value={dados.descricao} onChange={alterar} placeholder="Links, detalhes ou lembretes para você mesmo" /></div></div><div className="acoes-formulario"><button type="button" className="botao secundario" onClick={() => navegar('/tarefas')}>Cancelar</button><button className="botao primario" disabled={enviando}>{enviando ? 'Salvando...' : 'Salvar tarefa →'}</button></div></form></div></>;
}
