import { useEffect, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { api } from '../servicos/api';

export function PaginaDetalheTarefa() {
  const { id } = useParams();
  const navegar = useNavigate();
  const [dados, setDados] = useState(null);
  const [erro, setErro] = useState('');
  const [salvando, setSalvando] = useState(false);
  useEffect(() => { api.tarefa(id).then((resposta) => setDados(resposta.data.tarefa)).catch((erroApi) => setErro(erroApi.message)); }, [id]);
  const alterar = (evento) => setDados({ ...dados, [evento.target.name]: evento.target.value });
  async function salvar(evento) { evento.preventDefault(); setSalvando(true); setErro(''); try { await api.atualizarTarefa(id, { titulo: dados.titulo, materia: dados.materia, descricao: dados.descricao, tipo: dados.tipo, prioridade: dados.prioridade, dataEntrega: `${dados.dataEntrega}T${dados.horarioEntrega || '23:59'}:00` }); navegar('/tarefas'); } catch (erroApi) { setErro(erroApi.message); } finally { setSalvando(false); } }
  async function concluir() { try { const resposta = await api.concluirTarefa(id); setDados(resposta.data.tarefa); } catch (erroApi) { setErro(erroApi.message); } }
  async function excluir() { if (!window.confirm('Excluir esta tarefa?')) return; try { await api.excluirTarefa(id); navegar('/tarefas'); } catch (erroApi) { setErro(erroApi.message); } }
  if (!dados && !erro) return <div className="tela-carregando"><span className="marca-carregando">✦ Lembraí</span><span>Carregando tarefa...</span></div>;
  if (erro && !dados) return <div className="alerta erro" role="alert">A Lembraí não conseguiu carregar esta tarefa: {erro}</div>;
  const data = new Date(dados.dataEntrega);
  return <><header className="cabecalho-pagina"><div><p className="etiqueta">Lembraí · detalhes da atividade</p><h1>{dados.titulo}</h1><p className="subtitulo">Acompanhada pela Lembraí desde {new Date(dados.criadoEm).toLocaleDateString('pt-BR')}</p></div><div className="acoes"><button className="botao secundario" onClick={() => navegar('/tarefas')}>Voltar</button>{dados.status === 'pendente' && <button className="botao primario" onClick={concluir}>✓ Concluir</button>}</div></header>{erro && <div className="alerta erro">{erro}</div>}<div className="cartao formulario-cartao"><form onSubmit={salvar}><div className="formulario-grid"><div className="campo largo"><label htmlFor="titulo">Título</label><input id="titulo" name="titulo" value={dados.titulo} onChange={alterar} required /></div><div className="campo"><label htmlFor="materia">Matéria</label><input id="materia" name="materia" value={dados.materia || ''} onChange={alterar} /></div><div className="campo"><label htmlFor="tipo">Tipo</label><select id="tipo" name="tipo" value={dados.tipo} onChange={alterar}><option value="tarefa">Tarefa</option><option value="prova">Prova</option><option value="trabalho">Trabalho</option><option value="aula">Aula</option><option value="compromisso">Compromisso</option></select></div><div className="campo"><label htmlFor="dataEntrega">Data</label><input id="dataEntrega" name="dataEntrega" type="date" value={data.toISOString().slice(0, 10)} onChange={(evento) => setDados({ ...dados, dataEntrega: evento.target.value })} required /></div><div className="campo"><label htmlFor="horarioEntrega">Horário</label><input id="horarioEntrega" name="horarioEntrega" type="time" value={dados.horarioEntrega || data.toTimeString().slice(0, 5)} onChange={alterar} /></div><div className="campo"><label htmlFor="prioridade">Prioridade</label><select id="prioridade" name="prioridade" value={dados.prioridade} onChange={alterar}><option value="baixa">Baixa</option><option value="media">Média</option><option value="alta">Alta</option></select></div><div className="campo largo"><label htmlFor="descricao">Observações</label><textarea id="descricao" name="descricao" value={dados.descricao || ''} onChange={alterar} /></div></div><div className="acoes-formulario"><button type="button" className="botao perigo" onClick={excluir}>Excluir tarefa</button><button className="botao primario" disabled={salvando}>{salvando ? 'Salvando...' : 'Salvar alterações'}</button></div></form></div></>;
}
